# numpy vs python loop function
# with example which is faster


# python function

In [1]:
def seq(value):
    result=[]
    for v in value:
        result.append(v*v)
    return result    

In [2]:
sequare=range(100000)

In [3]:
%timeit seq(sequare)

17.8 ms ± 252 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# numpy function

In [4]:
import numpy as np
seq=np.arange(100000)
#time using vectiorized operation

In [8]:
%timeit seq

39.9 ns ± 0.899 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [9]:
%timeit seq*2

89.3 µs ± 949 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%timeit seq**2

87.5 µs ± 1.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# creating numpy array method

# Method 1(from python list)

In [20]:
import numpy as np
list=np.array([12,3,4,34,12,22])
list

array([12,  3,  4, 34, 12, 22])

In [17]:
type(list) #n deminsional array

numpy.ndarray

In [22]:
np.size(list)

6

In [25]:
list.dtype #datatype

dtype('int64')

In [31]:
#if you want to get float array
flt=np.array([1,3,34,65],dtype="float32")
flt

array([ 1.,  3., 34., 65.], dtype=float32)

In [34]:
#if there is any one no. become floating like this
flt=np.array([1,3,34,3.67]) #autmoaticly convet all no. in float if
flt #it show all the remaining no. convert into array

array([ 1.  ,  3.  , 34.  ,  3.67])

In [32]:
#if you want to get float array
flt=np.array([1,3,34,65],dtype="float64")
flt

array([ 1.,  3., 34., 65.])

# 1_dem=[1,23,34,54] one dimension array is our simple array its called vactor array  

# note: jitna us ka closing pranthics ho ga utna deminsion ho ga aray)

# 2_dem=[1,3,2,3,34],[23,32,11] Its 2D array also called Tensor/matrix


In [26]:
list.ndim # return the dimension of the array

1

# Method 2
# python range( ) function into numpy array

In [40]:
np.array(range(12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
np.shape(arr) # 12 show no. of elemnts in array and one comma show the one row that it is one row in it aray

(12,)

# Method 3 "a range " function:

In [44]:
np.arange(12)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
#increment  0 show starting 12 show last/total no. of value and 3 show no. of steps how many elments left b/w (0 ,12)
np.arange(0,12,3)

array([0, 3, 6, 9])

In [48]:
#decrement  0 show starting 12  show last/total no. of value  0 show backward value and -3 show no. of steps decress how many elments left decress b/w (0 ,12)
np.arange(12,0,-3)

array([12,  9,  6,  3])

In [53]:
#another method is linspace it devide 0 to 12 values into 10 parts 
np.linspace(0,12,10) #deiif equal b/w all by 10
#use for fake data when we create more fake data 

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ])

# expilicty convert/cast datatype of ndarray

In [54]:
arr=np.array([1,34,11,31])
arr.dtype #if u want to change the data type:

dtype('int64')

In [58]:
 #if u want to change the data type:
flt_arr=arr.astype(np.float)
flt_arr.dtype

dtype('float64')

In [59]:
flt_arr

array([ 1., 34., 11., 31.])

In [60]:
#if u wanr to  float into integer:
int=np.array([1.1,3.4,12.1,3.1])
int.dtype


dtype('float64')

In [62]:
flt=int.astype(np.int)
flt.dtype

dtype('int64')

In [61]:
#if u wanr to  float into integer:
int=np.array([1.1,3.4,12.1,3.1])
int.dtype
flt=int.astype(np.int)
flt.dtype

dtype('int64')

In [63]:
flt=int.astype(np.int)
flt

array([ 1,  3, 12,  3])

#  arthamtic operation with numpy array

In [67]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [71]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# accesing one Dimension Array elements from numpy array

In [78]:

arr=[12,33,1,73,11,55]
arr[0]

12

In [79]:
arr[3]

73

In [80]:
arr[-3]

73

In [81]:
arr[-0]

12

In [82]:
arr[-1]

55

In [83]:
arr[1],arr[-2]

(33, 11)

# two demensional array accesing

In [85]:
arr2=np.array([[1,4,2,35],[23,1,4,12]])
arr2

array([[ 1,  4,  2, 35],
       [23,  1,  4, 12]])

In [86]:
arr2.dtype

dtype('int64')

In [91]:
flt2=arr2.astype(np.float)
flt2

array([[ 1.,  4.,  2., 35.],
       [23.,  1.,  4., 12.]])

In [92]:
flt2.dtype

dtype('float64')

In [93]:
#similarly we can change float value into the int value


In [97]:
arr3=np.array([[1.4,2.4,3.5],[2.3,1.4,4.2]])
arr3

array([[1.4, 2.4, 3.5],
       [2.3, 1.4, 4.2]])

In [98]:
arr3.dtype

dtype('float64')

In [99]:
int3=arr3.astype(np.int)
int3

array([[1, 2, 3],
       [2, 1, 4]])

In [100]:
int3.dtype

dtype('int64')

In [105]:
 # reshape ki help sa kese b dimension ka matrix create karna bht asan ho jata ha 
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [108]:
arr.reshape(3,7) #it cannot be reshape bcz 7 *3 ia 21 no matrix make

ValueError: cannot reshape array of size 20 into shape (3,7)

In [109]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
#if u want to get the size of your array
np.size(arr2)

8

In [114]:
np.size(arr)

20

In [117]:
arr.shape # 20 no. of elemnt and  no colum

(20,)

In [116]:
#if u want to get row and colum of the array
arr2.shape #2 show row anda 4 show colum

(2, 4)

#  2d array convert into 1d array

In [143]:
arr2=np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
array1=arr2.reshape(20)
print(array)
#2-d array into 3-d array conversition
array2=np.arange(50).reshape(5,10) # we can write all it in one line and connect it by  dot.
array2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [146]:
array3=array2.reshape(2,5,5)
array3 # first  parameter "2" show depth and next prameter 5 show row and next parameter 5 column .

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

# all in one line

In [154]:
array=np.arange(20)
array
print("*************************************************************")
array1=array.reshape(20)
print(array)

*************************************************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [153]:
array=np.arange(20)
array
print("*************************************************************")
array1=array.reshape(20)
print(array)
#WE CAN WRITE BOTH IN ONE LINE LIKE UNDER WE WRITE
#2-d array into 3-d array conversition
array2=np.arange(50).reshape(5,10) # we can write all it in one line and connect it by  dot.
array2
print("*************************************************************")
array3=array2.reshape(2,5,5) # 2 NUMBER OF MATRIX/DEPTH KO SHOW KRTA HA  HUM IS KO ASA B PARH SKTA HAN KA HAMRA PAS 5 BY 5 KI 2 METRIX BNA GI
array3 # first  parameter "2" show depth and next prameter 5 show row and next parameter 5 column .

#THIS IS 3 DEMSION ARRAY BCZ THE CLOSING PRHANTICS IS 3    "]]]"

*************************************************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
*************************************************************


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [155]:
#DEPTH CHANGE B HOS SKTI HA ARRAY LIA LIKE HUM 3 ROW 2 COLUM KAR DA R DEPTH 5 KR DA TO 
array2=np.arange(50).reshape(5,10) # we can write all it in one line and connect it by  dot.
array2
print("*************************************************************")
array3=array2.reshape(5,2,5) # 5 NUMBER OF MATRIX/DEPTH KO SHOW KRTA HA  HUM IS KO ASA B PARH SKTA HAN KA HAMRA PAS 2 BY 5 KI 2 METRIX BNA GI
array3 # first  parameter "5" show depth and next prameter 2 show row and next parameter 5 column .
#DEPTH MEAN KITNI METRICS BNI HA 
#THIS IS 3 DEMSION ARRAY BCZ THE CLOSING PRHANTICS IS 3    "]]]"

*************************************************************


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

# ravel function convert array into 1-d array in one line


In [159]:
array2=np.arange(50).reshape(5,10) # we can write all it in one line and connect it by  dot.
array2
print("*************************************************************")
array3=array2.reshape(2,5,5) # 2 NUMBER OF MATRIX/DEPTH KO SHOW KRTA HA  HUM IS KO ASA B PARH SKTA HAN KA HAMRA PAS 5 BY 5 KI 2 METRIX BNA GI
array3 # first  parameter "2" show depth and next prameter 5 show row and next parameter 5 column .

#THIS IS 3 DEMSION ARRAY BCZ THE CLOSING PRHANTICS IS 3    "]]]"


*************************************************************


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [160]:
array=array2.ravel()
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [161]:
array2=np.arange(50).reshape(5,10) # we can write all it in one line and connect it by  dot.
array2
print("*************************************************************")
array3=array2.reshape(2,5,5) # 2 NUMBER OF MATRIX/DEPTH KO SHOW KRTA HA  HUM IS KO ASA B PARH SKTA HAN KA HAMRA PAS 5 BY 5 KI 2 METRIX BNA GI
array3 # first  parameter "2" show depth and next prameter 5 show row and next parameter 5 column .

#THIS IS 3 DEMSION ARRAY BCZ THE CLOSING PRHANTICS IS 3    "]]]"


# convert 2d or 3d into 1d
array=array2.ravel()
array

*************************************************************


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#  Diff b/w ravel vs reshape   (Note)
# ravel and reshape  array ka new view bana ka data hain mean ek copy tyr karta hain agr copy ma change karo ga to view ma b change aya ga agr orginal ma change karo ga wahi change copy ma aya ga...  example under here:}

  # ravel ma hum just us ki dimenson 2 ya 3-d sa 1-d ma krta hain
  # reshape ma hum us ki dimesion kam ziada kar skta hain


In [175]:
#for example hum apna aarray ma index 2 pa 32 add karna chahata to wo change orginal file ma b ho hoga
arr1=np.arange(30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [178]:
array2=arr1.reshape(3,5,2)
array2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [193]:
array3=array2.ravel()
array3

array([ 0,  1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [194]:
#for example hum apna aarray ma index 2 pa 32 add karna chahata to wo change orginal file ma b ho hoga



array3[2]=32 # its 32 add onn index 2
array3

array([ 0,  1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [195]:
#call original matrix 
arr1

array([ 0,  1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [209]:
# similarly ise trha reshape ma jo change aya ga wo us ki orginal ma b aya ga
array5=np.arange(25)
array5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [210]:
#for example hum apna aarray ma index 3 pa 23 add karna chahata to wo change orginal file ma b ho hoga
array6=array5.reshape(5,5)
array6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [214]:
#for example hum apna aarray ma index 3 pa 23 add karna chahata to wo change orginal file ma b ho hoga
array5[3]=23
array5

array([ 0,  1,  2, 23,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 23, 23,
       23, 23, 23, 20, 21, 22, 23, 24])

In [216]:
array6 #orginal ma change kia ha to copy ma b change a gaya haaa

array([[ 0,  1,  2, 23,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [23, 23, 23, 23, 23],
       [20, 21, 22, 23, 24]])

 # flatten function ki wja sa orginal ma change ni ho ga

In [261]:
array7=np.arange(25).reshape(5,5)
array7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [262]:
array8=array7.flatten()
array8# change in coopy but by using flatten the array  no change in orginal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [263]:
array8[2]=23
array8

array([ 0,  1, 23,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [265]:
array7 # no change in orginal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#  resize function  change in orginal array but does not untill we call orginal array

In [286]:
array9=np.arange(10).reshape(2,5)
array9 # 2d array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [287]:
array10=array9.resize(10)
array10 # when this cell run there is nothing show untill u call orginal array9


In [288]:
array9 # again convert into 1-d array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic slicing and indexing of multidimesion array


# indexing

In [290]:
array=np.arange(20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [291]:
#if u want to get one row from column
array[2] #get value of whole row index wise

array([ 8,  9, 10, 11])

In [294]:
#if u want to get wholw column from column
#: show wholw column uthana ha sath index no. 3 ka full column
array[:,3] #get value of whole column index wise

array([ 3,  7, 11, 15, 19])

In [295]:
#if u want to get any one elemnt from 2-d  array
array[3,2] # 3 show row mean in 3rd row and 2 show colum 2nd row ( 3rd row r 2nd colum ka elmnt utha do)

14

# slicing

# ( _ : _  , _ : _ )

# (start of row:end of row,start of column:end of column)

In [296]:
array=np.arange(20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [307]:
array[1:4]  #1 sa 4 ko chor ka sb hatha do 
#if u want to value from just row 
#uper wali sb ko choe ka baki sb row hatha da ga

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [310]:
array[:,1:3]   #agr row sb chaya but column 1 or 3 column  to ya sb ko hatha da ga siwaya 1 or 3rd  ka elmnt ka/
#if u want to value from just column
#baki wali column sb ko choe ka baki sb row utha da ga


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [311]:
 array[1:4,2:3] #1 or 4 ko chor bki row ka sb utha do
                #2colum r 3 column chor ka baki sb utha do

array([[ 6],
       [10],
       [14]])

# slicing vs indexing

# indexing: (target the elemnt of the array and the return is the indiviual (wo apni array ko represnt nai kar raha like it is dimesion less )   value or grop of value having their own data type)
------
array[2,3]


----

# slicing: (give us the part of the array that have same dimension ( jitni array ki dimesion ho gi wase hi dimesion da ga ) or shape as ther full array have)
array[2:3,4:3]
