# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

arr = np.arange(50)
arr = arr.reshape(2, len(arr) // 2)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ])
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
array = np.asarray([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
array = np.asarray([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]]) # --> 3 Dimensions
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [2]:
array = np.asarray([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5, 3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [6]:
arr = np.arange(25).reshape(5, 5)
print("Original: ", arr)
print("Squared: ", np.square(arr))

Original:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Squared:  [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [10]:
five_bysix = np.arange(30).reshape(5, 6)
print("Original: ", five_bysix)
print("Mean: ", np.mean(five_bysix))

Original:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [12]:
print("Original: ", five_bysix)
print("Standard Deviation: ", np.std(five_bysix))

Original:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Standard Deviation:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [ ]:
print("Original: ", five_bysix)
print("Mean: ", np.median(five_bysix))

## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
print("Original: ", five_bysix)
print("Transpose: ", np.transpose(five_bysix))

Original:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose:  [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [17]:
diagonal_array = np.arange(16).reshape(4, 4)
np.trace(diagonal_array)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [18]:
np.linalg.det(diagonal_array)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [20]:
arr = np.arange(100).reshape(10, 10)

print("5th percentile of arr : ", 
       np.percentile(arr, 5))
print("95th percentile of arr : ",
       np.percentile(arr, 95))


5th percentile of arr :  4.95
95th percentile of arr :  94.05


## Question:15

### How to find if a given array has any null values?

In [22]:
arr = np.arange(100).reshape(10, 10) # --> Does not have null
arr_has_null = np.asarray([[[1, 2, 3, 4, None], [5, 6, 7, 8]]]) # --> Has null

has_null = lambda arr: print("Array has null values") if None in arr else print("Array does not have any null values")

has_null(arr)

Array has null values
